# Generated by Django 4.2.5 on 2024-08-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_admindetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindetails',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
