# Generated by Django 4.2.5 on 2024-08-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_roomresults_status_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalhistory',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalhistory',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalhistory',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalhistory',
            name='selected_tab',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalhistory',
            name='upi_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
