# Generated by Django 4.2.5 on 2024-08-03 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_withdrawalhistory_account_holder_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='number_of_users',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='user3',
        ),
        migrations.AddField(
            model_name='challenge',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenge_opponent', to=settings.AUTH_USER_MODEL),
        ),
    ]
