# Generated by Django 4.2.5 on 2024-08-03 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_remove_challenge_number_of_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('R', 'Running'), ('C', 'Closed')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challenge_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent_challenges', to=settings.AUTH_USER_MODEL),
        ),
    ]
