# Generated by Django 4.2.5 on 2024-08-03 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_challenge_status_alter_challenge_challenge_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomresults',
            name='challenge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.challenge'),
            preserve_default=False,
        ),
    ]
