# Generated by Django 4.2.5 on 2024-08-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_roomresults_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposithistory',
            name='tag',
            field=models.CharField(choices=[('W', 'Winning'), ('D', 'Deposit')], default='D', max_length=1),
        ),
    ]
