# Generated by Django 4.2.5 on 2024-08-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_deposithistory_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='withdrawable_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
