# Generated by Django 4.2.5 on 2024-08-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_wallet_withdrawable_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomresults',
            name='admin_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
