# Generated by Django 4.2.5 on 2024-08-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_roomresults_admin_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomresults',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
