# Generated by Django 4.2.5 on 2024-08-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_roomresults_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposithistory',
            name='tag',
            field=models.CharField(choices=[('W', 'Winning'), ('D', 'Deposit'), ('A', 'Admin Deposit')], default='D', max_length=1),
        ),
    ]
